apiVersion : apps/v1
kind: Deployment
metadata:
  name: <deployment-name>
  namespace: <namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <deployment-name>
  template:
    metadata:
      labels:
        app: <deployment-name>
    spec:
      containers:
        - name: <deployment-name>
          image: <acr_server/dx29bioentity
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 0.48
              memory: "750Mi"
